services:
  backend:
    image: siddique7/mern-support-tickets-backend:latest
    container_name: support-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend.env

  frontend:
    image: siddique7/mern-support-tickets-frontend:latest
    container_name: support-frontend
    ports:
      - "80:80"
    depends_on:
      - backend